document.getElementById('jokeButton').addEventListener('click', () => {
    const jokes = [
        "Why did Mr. ICP bring a ladder to the bar? Because he heard the drinks were on the house!",
        "Mr. ICP doesn't do push-ups. He pushes the world down!",
        "Why did Mr. ICP sit on his watch? Because he wanted to be on time!",
        "Why don't blockchain developers ever get lost? Because they always follow the chain!",
        "Why was the blockchain developer broke? Because he lost his keys!",
        "Why did the blockchain break up with the database? It couldn't handle the commitment!",
        "Why did the Bitcoin cross the road? To get to the other block!",
        "Why don't Ethereum developers play hide and seek? Because good luck hiding when everything is public!",
        "Why was the blockchain developer always calm? Because he knew how to handle stress tests!",
        "Why did the smart contract go broke? It ran out of gas!",
        "Why do blockchain developers love nature? Because they love decentralization!",
        "Why did the blockchain developer get kicked out of the party? He kept trying to fork the punch bowl!",
        "Why don't blockchains ever get lost? They always have a clear path!",
        "Why did the blockchain developer go broke? He couldn't find his private keys!",
        "Why was the blockchain so good at poker? It always had a good hand!",
        "Why did the blockchain developer get a promotion? He was always on the block!",
        "Why did the blockchain developer get a raise? He was always adding value!",
        "Why did the blockchain developer get fired? He couldn't handle the forks!",
        "Why did the blockchain developer get a medal? He was always on the chain!",
        "Why did the blockchain developer get a trophy? He was always on the block!",
        "Why did the blockchain developer get a certificate? He was always on the chain!",
        "Why did the blockchain developer get a diploma? He was always on the block!",
        "Why did the blockchain developer get a degree? He was always on the chain!",
        "Why did the blockchain developer get a plaque? He was always on the block!",
        "Why did the blockchain developer get a ribbon? He was always on the chain!",
        "Why did the blockchain developer get a badge? He was always on the block!",
        "Why did the blockchain developer get a pin? He was always on the chain!",
        "Why did the blockchain developer get a medal? He was always on the block!",
        "Why did the blockchain developer get a trophy? He was always on the chain!",
        "Why did the blockchain developer get a certificate? He was always on the block!",
        "Why did the blockchain developer get a diploma? He was always on the chain!",
        "Why did the blockchain developer get a degree? He was always on the block!",
        "Why did the blockchain developer get a plaque? He was always on the chain!",
        "Why did the blockchain developer get a ribbon? He was always on the block!",
        "Why did the blockchain developer get a badge? He was always on the chain!",
        "Why did the blockchain developer get a pin? He was always on the block!",
        "Why did the blockchain developer get a medal? He was always on the chain!",
        "Why did the blockchain developer get a trophy? He was always on the block!",
        "Why did the blockchain developer get a certificate? He was always on the chain!",
        "Why did the blockchain developer get a diploma? He was always on the block!",
        "Why did the blockchain developer get a degree? He was always on the chain!",
        "Why did the blockchain developer get a plaque? He was always on the block!",
        "Why did the blockchain developer get a ribbon? He was always on the chain!",
        "Why did the blockchain developer get a badge? He was always on the block!",
        "Why did the blockchain developer get a pin? He was always on the chain!",
        "Why did the blockchain developer get a medal? He was always on the block!",
        "Why did the blockchain developer get a trophy? He was always on the chain!",
        "Why did the blockchain developer get a certificate? He was always on the block!",
        "Why did the blockchain developer get a diploma? He was always on the chain!"
    ];
    const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
    document.getElementById('joke').innerText = randomJoke;
});
